services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: bkp-libretranslate
    ports:
      - "5000:5000"
    environment:
      LT_HOST: 0.0.0.0
      LT_PORT: 5000
      LT_LOAD_ONLY: en,es,ru,sk
    restart: unless-stopped
